### ISSUE TITLE
Why console printout `import re`?

### ISSUE THREAD

**Issue by cdeil** [iminuit/iminuit#232] opened 2018-06-08 12:08 UTC
With iminuit master and the example from the docs page I get this output.
Why is there a printout of `import re`!?

@HDembinski - Do you know / see the same? Or should I investigate?

```
In [3]: %paste
from iminuit import Minuit
def f(x, y, z):
    return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
m = Minuit(f)
m.migrad()
print(m.values)  # {'x': 2,'y': 3,'z': 4}
print(m.errors)  # {'x': 1,'y': 1,'z': 1}

## -- End pasted text --
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: errordef is not given. Default to 1.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter x does not have initial value. Assume 0.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter x is floating but does not have initial step size. Assume 1.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter y does not have initial value. Assume 0.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter y is floating but does not have initial step size. Assume 1.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter z does not have initial value. Assume 0.
  import re
/Users/deil/software/anaconda3/envs/iminuit/bin/ipython:4: InitialParamWarning: Parameter z is floating but does not have initial step size. Assume 1.
  import re
{'x': 2.0000000000047327, 'y': 3.000000000007099, 'z': 4.000000000009465}
{'x': 1.0000000000000409, 'y': 1.0000000000002762, 'z': 0.9999999999998322}
```

**Comment by HDembinski** [comment] 2018-06-14 13:06
Hi, I can confirm this with IPython, but it does not appear in the normal Python interpreter. Also, it does not appear when the function is a lambda, only when it is a real function.

**Comment by HDembinski** [comment] 2018-06-14 13:07
Minimal code:
```
from iminuit import Minuit
def f(x): return x** 2
Minuit(f)
```

**Comment by HDembinski** [comment] 2018-06-14 13:48
I did some reading how the `warnings` module works. Whenever a warning is raised, the warning is formatted with the standard implementation of this function.
`warnings.formatwarning(message, category, filename, lineno[, line])`
See https://docs.python.org/2/library/warnings.html#warnings.formatwarning
When `line` is not given (which we don't do), it uses the line specified by filename and lineno.

We call `warn` from Cython, and it gets confused. It uses the IPython instance as filename, and some lineno which seems arbitrary (it is certainly not the line where `warn` was called in _libiminuit.pyx`). In my case, it is lineno 4. Since IPython is a script with the content
```
#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from IPython import start_ipython

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())
```
Line number 4 is just `import re`. Now we know at least where it comes from.

**Comment by cdeil** [comment] 2018-06-14 14:11
@HDembinski - Thanks for figuring this out.

If I understand correctly in #233 you monkey-patch  `warnings.formatwarning`.
This fixes the issue, but it probably also leads to the side effect that just `import iminuit` might lead to changes in warnings formatting and head-scratching for others.

I found only one post on this issue, proposing a different hack:
https://stackoverflow.com/questions/2647128/emitting-cythonic-warnings

Ask on the Cython mailing list for advice / how others have handled the issue?

**Comment by cdeil** [comment] 2018-06-15 07:34
I've asked on https://groups.google.com/forum/#!forum/cython-users
I think the mailing list is moderator approved, but the message should appear soon.
Let's wait a few days for answers there and then decide what change to make in iminuit.

**Comment by HDembinski** [comment] 2018-06-15 08:05
I think the answer given in https://stackoverflow.com/questions/2647128/emitting-cythonic-warnings
could work for us, that you found. I will give it a quick try. The solution in this case has no side effects, as far as I can see. In any case, the problem is in Cython and we can only work around it.

**Comment by cdeil** [comment] 2018-06-15 08:11
https://groups.google.com/forum/#!topic/cython-users/hLNi1y4-Htg

**Comment by HDembinski** [comment] 2018-06-15 08:12
Thank you for the comprehensive posting, this looks great. I hope we get a reply.

**Comment by HDembinski** [comment] 2018-06-15 08:31
This also seems related: https://github.com/cython/cython/issues/1755
The stack frames in Cython are faked, but only when an exception is raised. This is not done when a warning is raised, which is why warnings behave so strangely.

**Comment by cdeil** [comment] 2018-06-15 09:00
@HDembinski - See https://github.com/ipython/ipython/issues/11188 and
https://groups.google.com/forum/#!topic/cython-users/hLNi1y4-Htg

My suggestion would be to just wait and see if / what changes are made in ipython or Cython, and only if the problem is still there say in a month or two, make a change in iminuit.

**Comment by HDembinski** [comment] 2018-06-15 09:39
Ok, I tried to play around with the code a bit and found no solution. I will wait.

**Comment by cdeil** [comment] 2018-06-20 16:01
Removing v1.3 milestone. It's been like this for years and no user complained.
Probably this issue will be resolved within the next months by the iminuit or Cython folks.

**Comment by HDembinski** [comment] 2018-09-11 00:49
fixed in master

**Closed by HDembinski** 2018-09-11 00:49 UTC
Labels: bug

**Comment by cdeil** [comment] 2018-09-11 06:49
Yippie!
