### ISSUE TITLE
'print_level=2' doesn't work in python 3

### ISSUE THREAD

**Issue by mattngc** [iminuit/iminuit#165] opened 2015-08-06 16:33 UTC
Levels 0 and 1 both work as expected, but not at level 2.

**Comment by cdeil** [comment] 2015-11-04 20:53
@mattngc – Print level for which method doesn't work as expected?

If you could produce a minimal code example that shows the issue, that would help a lot to pin this down and fix it quickly (and add a regression test to make sure it stays fixed). You're saying this gives the output you expect on Python 2 but not Python 3?

**Comment by piti118** [comment] 2016-05-01 05:39
This is because when we move from Minuit1.xx to Minuit2.xx I probably forgot to add some print function.

Print level 2 comes from Modified version of Minuit.

**Comment by HDembinski** [comment] 2018-03-03 20:59
@mattngc Hi, if you are still reading this, could you try the latest master version to whether your problem was solved?

**Comment by mattngc** [comment] 2018-03-04 12:11
Hi @HDembinski , I haven't used this library for a while. So not easy for me to test straight away. But thanks for looking at it.

**Comment by cdeil** [comment] 2018-03-04 15:54
I'm closing this issue now.

If anyone still finds an issue in the future related to this, please re-open or file a new one!

**Closed by cdeil** 2018-03-04 15:54 UTC
Labels: bug
