### ISSUE TITLE
Attribute error when calling `migrad`

### ISSUE THREAD

**Issue by xaratustrah** [iminuit/iminuit#189] opened 2016-11-02 09:19 UTC
Hi and thanks for the nice work. I am not sure if this is a bug, but I encounter an **Atribute error** when calling `migrad` using `*` parameters. I have put the error description [here on SO](http://stackoverflow.com/q/40360615/5177935). Any hints is appreciated.

**Comment by cdeil** [comment] 2016-11-02 21:13
@xaratustrah - Thanks for reporting this.

Please see http://stackoverflow.com/a/40389851/498873

I think for iminuit there's two action items here:

- [ ] Implement input validation in `Minuit.__init__`
- [ ] Add one or more documentation examples that use `forced_parameters` to avoid argument inspection.

I don't have time for this at the moment.
Pull requests welcome!

**Comment by cdeil** [comment] 2016-11-02 21:19
Just to be clear: the cause of the error is that you're passing a float `frontend=0.4` to `Minuit.__init__`, which gets stored in `self.frontend` here:
```
self.frontend = self._auto_frontend() if frontend is None else frontend
```
https://github.com/iminuit/iminuit/blob/master/iminuit/_libiminuit.pyx#L343

and then later this line
```
self.frontend.print_banner('MIGRAD')
```
https://github.com/iminuit/iminuit/blob/master/iminuit/_libiminuit.pyx#L439

causes the `AttributeError`:
```
$ python fit.py 
57.1645229329
fit.py:16: InitialParamWarning: errordef is not given. Default to 1.
  m = iminuit.Minuit(minimize_me, *p)
Traceback (most recent call last):
  File "fit.py", line 17, in <module>
    m.migrad() # fails!
  File "iminuit/_libiminuit.pyx", line 439, in iminuit._libiminuit.Minuit.migrad (iminuit/_libiminuit.cpp:5074)
AttributeError: 'float' object has no attribute 'print_banner'
```

So it's clear what to do: add a regression test for this and then input validation in `Minuit.__init__`.

**Comment by xaratustrah** [comment] 2016-11-03 11:41
Thank you for taking care of this so far. I am not sure if the following suggestion would be useful and maybe easier. Since parameter names are needed and actually quite good in **iminuit**, in a manner _similar_ to `scipy.optimize`:

```
from scipy.optimize import curve_fit
p = [1,2,3,4,5]
curve_fit(fit_function, x_data, y_data, p0 = p)
```

one might be able to give the parameters either as a list, or as a dictionary by `params=XYZ`. In the former case, a check on `isinstance` might be enough. If the user has passed a list, then using [your code from the SO reply](http://stackoverflow.com/a/40389851/5177935) gives them some default names.

In a later stage, the user can always change the name of the parameters, if needed.

**Comment by cdeil** [comment] 2016-11-03 12:43
@xaratustrah - IMO `Minuit.__init__` is already too complex, with the argument parsing and `forced_parameters` special case. My preference would be to add one or more extra alternative constructors as Python [classmethods](http://stackoverflow.com/a/19305443/498873).

IMO the `scipy.optimize.curve_fit` isn't in scope for `iminuit` itself. There's the [probfit](https://github.com/iminuit/probfit) package built on `iminuit` that will construct a chi^2 cost function for the user, just like `scipy.optimize.curve_fit` does.

But the case of "I don't care about parameter names, I just have a list of parameters" is a very common one, and the current solution with `forced_parameters` isn't great (and documentation is missing). So +1 to add a classmethod that's similar to the [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.html) API, i.e. just takes a list of parameter start values.

I'd be happy to continue discussing API / implementation specifics, I think that would be an important addition to iminuit, but it only makes sense if someone is volunteering to implement it in the near future (I don't have time).

**Comment by cdeil** [comment] 2018-06-20 16:07
@HDembinski - Close?

I think your recent additions still need high-level docs descriptions, but is keeping this issue helpful?

**Comment by HDembinski** [comment] 2018-06-21 09:32
Turns out that the `__init__` was improved in the meantime (not by me) and throws a proper error which is indicative of the problem. So there is nothing else to be done. We will improve the docs anyway, so I am closing this issue.

**Closed by HDembinski** 2018-06-21 09:32 UTC
Labels: enhancement
