### ISSUE TITLE
Analytical gradient

### ISSUE THREAD

**Issue by rodiram** [iminuit/iminuit#140] opened 2015-02-20 22:54 UTC
Great work ! .. but, it seems there is no possibility to input analytical gradients. I am doing some heavy fitting with more than 3000 parameters and my fit that converge easily with Minuit2 do not in iminuit with no  analytical gradients input. That's too bad because that's the strength of Minuit which is mostly used (I think ..) in particle physics or astrophysics for heavy fitting and less for simple linear regression. Any plan to add that in the future ?
Also, I noticed that often even when EDM < GOAL EDM the status is 'is_valid': False. I guess it should not be that way.

**Comment by ycopin** [comment] 2015-03-30 15:43
I think 1st point is already addressed by #125, and 2nd point by #73.

**Comment by cdeil** [comment] 2015-04-20 20:02
@rodiram – I think @ycopin is right and this is a duplicate of issue #125 or #73.
Closing this issue now ... you can click the "subscribe" button on the others if you want to get email notifications on new comments.
And any contributions to `iminuit` are very welcome of course!

**Closed by cdeil** 2015-04-20 20:02 UTC
