### ISSUE TITLE
Migrad makes more calls than given by ncall 

### ISSUE THREAD

**Issue by VoRodin** [iminuit/iminuit#227] opened 2018-04-17 10:55 UTC
Hello guys,

I am trying to minimize function using a limited number of steps(default=10000),
Next line does not work as expected and migrad continue to do new iterations.
Minuit.migrad(ncall=50)

Best regards

**Comment by HDembinski** [comment] 2018-04-18 11:18
Hi, thanks for reporting this.

I can reproduce this. We need to improve the docs. Unfortunately, we cannot fix this, because it is a behavior of MINUIT. The current behavior actually makes some sense if you understand how MINUIT works.

MINUIT does a form of gradient descent. This works in discrete steps. In each step, MINUIT computes the gradient of the function and then does a line search along the gradient to find the new minimum along the line. There are more details, but this is enough to understand why the call limit is not strictly obeyed.

When you compute a gradient numerically, you already do several function calls. There are even more function calls involved in the line search to the new minimum. MINUIT only checks the call limit after at least one iteration of this algorithm, therefore it will not obey the call limit exactly. In particular, it will use a minimum number of calls every time, whatever the value you use as a limit.

**Comment by HDembinski** [comment] 2018-06-28 09:20
The documentation is improved in PR #251.

**Comment by HDembinski** [comment] 2018-06-28 09:20
I am closing this issue.

**Closed by HDembinski** 2018-06-28 09:20 UTC
Labels: needs documentation
